"""
Script to inspect preprocessed GRPO data for contamination.

This script checks if the contamination text "You are an AI assistant that helps
people find information..." appears in the preprocessed GRPO training data.
"""

from datasets import load_from_disk
import sys

def inspect_grpo_data():
    """Load and inspect GRPO preprocessed data for contamination."""

    print("Loading preprocessed GRPO data...")
    dataset = load_from_disk('./data/processed/grpo')

    print(f"\nDataset structure: {dataset}")
    print(f"\nAvailable fields: {dataset['train'].column_names}")
    print(f"\nTrain examples: {len(dataset['train'])}")
    print(f"Validation examples: {len(dataset['validation'])}")

    # Check for contamination text patterns
    contamination_markers = [
        "you are an ai assistant",
        "helps people find information",
        "your task is to answer",
        "answer as faithfully as you can",
    ]

    print("\n" + "="*80)
    print("CHECKING FOR CONTAMINATION IN TRAINING DATA")
    print("="*80)

    # Check all training examples for contamination
    contaminated_examples = []
    for i in range(len(dataset['train'])):
        example = dataset['train'][i]
        query_text = example['query'].lower()

        # Check if any contamination marker is present
        for marker in contamination_markers:
            if marker in query_text:
                contaminated_examples.append((i, marker, example['query']))
                break

    print(f"\n📊 SCAN RESULTS:")
    print(f"   Total training examples scanned: {len(dataset['train'])}")
    print(f"   Contaminated examples found: {len(contaminated_examples)}")
    print(f"   Contamination rate: {len(contaminated_examples)/len(dataset['train'])*100:.2f}%")

    if contaminated_examples:
        print(f"\n⚠️  CONTAMINATION DETECTED IN TRAINING DATA!")
        print(f"\nShowing first 5 contaminated examples:")
        for idx, (i, marker, query) in enumerate(contaminated_examples[:5]):
            print(f"\n--- Contaminated Example {i} ---")
            print(f"Matched marker: '{marker}'")
            print(f"Query content:\n{query[:600]}...")
    else:
        print(f"\n✓ NO CONTAMINATION FOUND in training data queries")
        print(f"\nShowing first 3 clean examples:")
        for i in range(min(3, len(dataset['train']))):
            example = dataset['train'][i]
            print(f"\n--- Example {i} ---")
            print(f"{example['query'][:500]}...")

    # Check validation split
    print("\n\n" + "="*80)
    print("CHECKING VALIDATION SPLIT")
    print("="*80)

    val_contaminated = []
    for i in range(len(dataset['validation'])):
        example = dataset['validation'][i]
        query_text = example['query'].lower()

        for marker in contamination_markers:
            if marker in query_text:
                val_contaminated.append((i, marker, example['query']))
                break

    print(f"\n📊 VALIDATION RESULTS:")
    print(f"   Total validation examples scanned: {len(dataset['validation'])}")
    print(f"   Contaminated examples found: {len(val_contaminated)}")
    print(f"   Contamination rate: {len(val_contaminated)/len(dataset['validation'])*100:.2f}%")

    if val_contaminated:
        print(f"\n⚠️  CONTAMINATION in validation data!")
        print(f"\nShowing first 2 contaminated validation examples:")
        for idx, (i, marker, query) in enumerate(val_contaminated[:2]):
            print(f"\n--- Val Example {i} ---")
            print(f"Matched marker: '{marker}'")
            print(f"{query[:600]}...")
    else:
        print(f"\n✓ NO CONTAMINATION in validation queries")

    print("\n" + "="*80)
    print("CONCLUSION")
    print("="*80)

    if not contaminated_examples and not val_contaminated:
        print("\n✓ The preprocessed GRPO data is CLEAN - no contamination found.")
        print("\nThis means the contamination text seen in model outputs is likely:")
        print("  1. Coming from the base Qwen model's pre-training data")
        print("  2. Being generated by the model during inference")
        print("  3. Not present in our fine-tuning data")
        print("\nRecommendation: Fix the answer extraction logic in evaluate_model.py")
        print("to handle contaminated model outputs by truncating after 'Therefore:'")
    else:
        print("\n⚠️  CONTAMINATION FOUND in preprocessed data!")
        print("\nThis means the contamination was introduced during data preprocessing.")
        print("\nRecommendation: Fix data_preprocessing.py to remove contamination")
        print("and rerun preprocessing + training.")

if __name__ == "__main__":
    inspect_grpo_data()
